var search={
  "Aachen": "http://data.archaeology.link/data/samian/loc_pc_2000023",
  "Abella": "http://data.archaeology.link/data/samian/loc_pc_2000057",
  "Activity Instances Collection": "http://data.archaeology.link/data/samian/Activity_collection",
  "Albi": "http://data.archaeology.link/data/samian/loc_pc_2000102",
  "Ampurias": "http://data.archaeology.link/data/samian/loc_pc_2000086",
  "And\u00fajar": "http://data.archaeology.link/data/samian/loc_pc_2000058",
  "Arenzana de Abajo": "http://data.archaeology.link/data/samian/loc_pc_2000059",
  "Arenzana de Arriba": "http://data.archaeology.link/data/samian/loc_pc_2000060",
  "Arezzo": "http://data.archaeology.link/data/samian/loc_pc_2000087",
  "Aspiran": "http://data.archaeology.link/data/samian/loc_pc_2000008",
  "Avocourt": "http://data.archaeology.link/data/samian/loc_pc_2000024",
  "Baden": "http://data.archaeology.link/data/samian/loc_pc_2000025",
  "Banassac": "http://data.archaeology.link/data/samian/loc_pc_2000002",
  "Ba\u00f1os de R\u00edo Tob\u00eda": "http://data.archaeology.link/data/samian/loc_pc_2000061",
  "Bern": "http://data.archaeology.link/data/samian/loc_pc_2000026",
  "Bezares": "http://data.archaeology.link/data/samian/loc_pc_2000062",
  "Blickweiler": "http://data.archaeology.link/data/samian/loc_pc_2000027",
  "Bliesbruck": "http://data.archaeology.link/data/samian/loc_pc_2000028",
  "Bobadilla": "http://data.archaeology.link/data/samian/loc_pc_2000063",
  "Boucheporn": "http://data.archaeology.link/data/samian/loc_pc_2000029",
  "Bram": "http://data.archaeology.link/data/samian/loc_pc_2000010",
  "Bronchales": "http://data.archaeology.link/data/samian/loc_pc_2000064",
  "Cales": "http://data.archaeology.link/data/samian/loc_pc_2000088",
  "Camprovi\u00edn": "http://data.archaeology.link/data/samian/loc_pc_2000065",
  "Carrade": "http://data.archaeology.link/data/samian/loc_pc_2000004",
  "Ch\u00e9mery-Faulquemont": "http://data.archaeology.link/data/samian/loc_pc_2000030",
  "Cincelli": "http://data.archaeology.link/data/samian/loc_pc_2000089",
  "Colchester": "http://data.archaeology.link/data/samian/loc_pc_2000055",
  "Corella": "http://data.archaeology.link/data/samian/loc_pc_2000066",
  "Cornella de Terri": "http://data.archaeology.link/data/samian/loc_pc_2000067",
  "Cournon": "http://data.archaeology.link/data/samian/loc_pc_2000014",
  "Covarrubias": "http://data.archaeology.link/data/samian/loc_pc_2000068",
  "Crambade": "http://data.archaeology.link/data/samian/loc_pc_2000005",
  "Eincheville": "http://data.archaeology.link/data/samian/loc_pc_2000031",
  "Eschweilerhof": "http://data.archaeology.link/data/samian/loc_pc_2000032",
  "Espalion": "http://data.archaeology.link/data/samian/loc_pc_2000006",
  "Estollo": "http://data.archaeology.link/data/samian/loc_pc_2000069",
  "Granada": "http://data.archaeology.link/data/samian/loc_pc_2000070",
  "Gueugnon": "http://data.archaeology.link/data/samian/loc_pc_2000015",
  "Haute-Yutz": "http://data.archaeology.link/data/samian/loc_pc_2000033",
  "Heiligenberg": "http://data.archaeology.link/data/samian/loc_pc_2000034",
  "Herrera de Pisuerga": "http://data.archaeology.link/data/samian/loc_pc_2000090",
  "Horbourg": "http://data.archaeology.link/data/samian/loc_pc_2000035",
  "Ittenwiller": "http://data.archaeology.link/data/samian/loc_pc_2000036",
  "Jaulges-Villiers-Vineux": "http://data.archaeology.link/data/samian/loc_pc_2000037",
  "Jonqui\u00e8res, Saint Saturnin": "http://data.archaeology.link/data/samian/loc_pc_2000007",
  "Kr\u00e4herwald": "http://data.archaeology.link/data/samian/loc_pc_2000051",
  "La Graufesenque": "http://data.archaeology.link/data/samian/loc_pc_2000001",
  "La Madeleine": "http://data.archaeology.link/data/samian/loc_pc_2000038",
  "La Rioja": "http://data.archaeology.link/data/samian/loc_pc_2000071",
  "Lavoye": "http://data.archaeology.link/data/samian/loc_pc_2000039",
  "Le Pont des R\u00e8mes": "http://data.archaeology.link/data/samian/loc_pc_2000041",
  "Le Rozier": "http://data.archaeology.link/data/samian/loc_pc_2000003",
  "Lehen": "http://data.archaeology.link/data/samian/loc_pc_2000040",
  "Les Allieux": "http://data.archaeology.link/data/samian/loc_pc_2000042",
  "Les Martres-de-Veyre": "http://data.archaeology.link/data/samian/loc_pc_2000018",
  "Lezoux": "http://data.archaeology.link/data/samian/loc_pc_2000016",
  "Li\u00e9dena": "http://data.archaeology.link/data/samian/loc_pc_2000072",
  "Location Instances Collection": "http://data.archaeology.link/data/samian/Location_collection",
  "Lubi\u00e9": "http://data.archaeology.link/data/samian/loc_pc_2000017",
  "Luxeuil-les-Bains": "http://data.archaeology.link/data/samian/loc_pc_2000043",
  "Lyon": "http://data.archaeology.link/data/samian/loc_pc_2000100",
  "Manjarr\u00e9s": "http://data.archaeology.link/data/samian/loc_pc_2000073",
  "Micasasa": "http://data.archaeology.link/data/samian/loc_pc_2000099",
  "Mittelbronn": "http://data.archaeology.link/data/samian/loc_pc_2000044",
  "Montans": "http://data.archaeology.link/data/samian/loc_pc_2000011",
  "Montroig": "http://data.archaeology.link/data/samian/loc_pc_2000075",
  "Mougon": "http://data.archaeology.link/data/samian/loc_pc_2000019",
  "M\u00e1laga": "http://data.archaeology.link/data/samian/loc_pc_2000074",
  "Narbonne": "http://data.archaeology.link/data/samian/loc_pc_2000009",
  "Nou\u00e2tre": "http://data.archaeology.link/data/samian/loc_pc_2000020",
  "N\u00fcrtingen": "http://data.archaeology.link/data/samian/loc_pc_2000045",
  "Offemont": "http://data.archaeology.link/data/samian/loc_pc_2000046",
  "Pamplona": "http://data.archaeology.link/data/samian/loc_pc_2000076",
  "Pantoja": "http://data.archaeology.link/data/samian/loc_pc_2000077",
  "Pfaffenhofen": "http://data.archaeology.link/data/samian/loc_pc_2000053",
  "Pisa": "http://data.archaeology.link/data/samian/loc_pc_2000091",
  "Po Valley": "http://data.archaeology.link/data/samian/loc_pc_2000092",
  "Point Instances Collection": "http://data.archaeology.link/data/samian/Point_collection",
  "Ponte a Buriano": "http://data.archaeology.link/data/samian/loc_pc_2000093",
  "Pozzuoli": "http://data.archaeology.link/data/samian/loc_pc_2000094",
  "Pradej\u00f3n": "http://data.archaeology.link/data/samian/loc_pc_2000078",
  "ProductionCentre Instances Collection": "http://data.archaeology.link/data/samian/ProductionCentre_collection",
  "Pulborough": "http://data.archaeology.link/data/samian/loc_pc_2000056",
  "Rheinzabern": "http://data.archaeology.link/data/samian/loc_pc_2000047",
  "Rodez": "http://data.archaeology.link/data/samian/loc_pc_2000103",
  "Ruidoms": "http://data.archaeology.link/data/samian/loc_pc_2000079",
  "Sabadell": "http://data.archaeology.link/data/samian/loc_pc_2000080",
  "Sagone": "http://data.archaeology.link/data/samian/loc_pc_2000101",
  "Saint-Sauveur": "http://data.archaeology.link/data/samian/loc_pc_2000012",
  "Schwabegg": "http://data.archaeology.link/data/samian/loc_pc_2000050",
  "Scoppieto": "http://data.archaeology.link/data/samian/loc_pc_2000095",
  "Sinzig": "http://data.archaeology.link/data/samian/loc_pc_2000048",
  "Solsona": "http://data.archaeology.link/data/samian/loc_pc_2000081",
  "Sot\u00e9s": "http://data.archaeology.link/data/samian/loc_pc_2000082",
  "Talavera de la Reina": "http://data.archaeology.link/data/samian/loc_pc_2000083",
  "Tiermes": "http://data.archaeology.link/data/samian/loc_pc_2000084",
  "Torrita di Siena": "http://data.archaeology.link/data/samian/loc_pc_2000096",
  "Toulon-sur-Allier": "http://data.archaeology.link/data/samian/loc_pc_2000021",
  "Tricio": "http://data.archaeology.link/data/samian/loc_pc_2000085",
  "Trier": "http://data.archaeology.link/data/samian/loc_pc_2000049",
  "Val\u00e9ry": "http://data.archaeology.link/data/samian/loc_pc_2000013",
  "Vasanello": "http://data.archaeology.link/data/samian/loc_pc_2000097",
  "Venosa": "http://data.archaeology.link/data/samian/loc_pc_2000098",
  "Vichy, Terre Franche": "http://data.archaeology.link/data/samian/loc_pc_2000022",
  "Waiblingen": "http://data.archaeology.link/data/samian/loc_pc_2000052",
  "Westerndorf": "http://data.archaeology.link/data/samian/loc_pc_2000054"
}